name: Deploy to Remote Server

on:
  push:
    branches:
      - main  # Trigger deployment only when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add SSH host to known hosts
      run: echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@ec2-13-60-199-107.eu-north-1.compute.amazonaws.com << 'EOF'
          cd ~/Portal/Portal  # Navigate to your repository on the server
          git checkout -- public/CVMenachemParente.pdf
          git pull origin main  # Pull the latest changes
          sudo systemctl stop portal.service  # Stop the service
          npm install  # Ensure dependencies are up to date
          npm run build  # Build the app
          sudo systemctl start portal.service  # Restart the service
        EOF
